.TH "TPNote3/TPNote3.cpp" 3 "DocExercice3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPNote3/TPNote3.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <opencv2/core/core\&.hpp>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <opencv2/imgproc\&.hpp>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <bitset>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBtaille\fP   7"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI ": fonction principale "
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define taille   7"

.SH "Documentation des fonctions"
.PP 
.SS "int main ()"

.PP
: fonction principale 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DocExercice3 à partir du code source\&.
